[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"  # cartella output build

[[redirects]]
  from = "/*"
  to = "/index.html"cd netlify/functions/send-booking-email/
touch index.js
code index.js  # o nano

  status = 200
